name: MLOps Pipeline

on:
  #push:
   # branches:
    #  - main # Trigger workflow on push to the main branch
  #pull_request:
   # branches:
    #  - main # Trigger workflow on pull requests to the main branch
  workflow_dispatch: # Allow manual triggers

jobs:


  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_2}}

      - name: Show Logged In Subscription
        run: az account show
          
  get-config:
     uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
     with: 
        file_name: config-infra-prod.yml
        creds: ${{secrets.AZURE_CREDENTIALS_2}}

  register-environment:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
    with:
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
      environment_file: mlops/azureml/train/train-env.yml
      conda_file: data-science/environment/train-conda.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}


  register-dataset:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@main
    with:
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
      name: used-cars-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}
    
  create-compute:
    needs: [get-config,register-environment,register-dataset]
    uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
    with:
      cluster_name: cpu_cluster
      size: Standard_DS11_v2
      min_instances: 0
      max_instances: 1
      cluster_tier: dedicated
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}

  run-pipeline:
    needs: [get-config,register-environment,create-compute,register-dataset]
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
      parameters-file: mlops/azureml/train/pipeline.yml
      job-name: test
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}

  register-environment-deploy:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
    with:
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
      environment_file: mlops/azureml/deploy/online/deploy-env.yml
      conda_file: data-science/environment/deploy-conda.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}


  create-endpoint:
    needs: [get-config,run-pipeline]
    uses: Azure/mlops-templates/.github/workflows/create-endpoint.yml@main
    with:
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
      endpoint_file: mlops/azureml/deploy/online/online-endpoint.yml
      endpoint_name: used-car-price-endpoint
      endpoint_type: online
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}

  create-deployment:
    uses: Azure/mlops-templates/.github/workflows/create-deployment.yml@main
    needs: [get-config,register-environment-deploy,create-endpoint]
    with:
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
      endpoint_file: mlops/azureml/deploy/online/online-deployment.yml
      endpoint_name: used-car-price-endpoint
      deployment_name: used-car-price-deployment
      endpoint_type: online
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}

  allocate-traffic:
    uses: Azure/mlops-templates/.github/workflows/allocate-traffic.yml@main
    needs: [get-config,create-deployment]
    with:
      resource_group: ${{needs.get-config.outputs.resource_group}}
      workspace_name: ${{needs.get-config.outputs.aml_workspace}}
      traffic_allocation: used-car-price-online-dp=100
      endpoint_name: used-car-price-endpoint
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS_2}}
   
